#!/bin/sh

for file in *.csv; do
    cp "$file" "${file}.bu"
done

for file in *.csv; do
    head -n 1 "$file" >"${file%.*}-WC.csv"
    head -n 1 "$file" >"${file%.*}-EC.csv"

    rg ,CA, "$file" >>"${file%.*}-WC.csv"
    sed -i '/,CA,/d' "$file"
    rg ,WA, "$file" >>"${file%.*}-WC.csv"
    sed -i '/,WA,/d' "$file"
    rg ,OR, "$file" >>"${file%.*}-WC.csv"
    sed -i '/,OR,/d' "$file"
    rg ,NV, "$file" >>"${file%.*}-WC.csv"
    sed -i '/,NV,/d' "$file"
    rg ,HI, "$file" >>"${file%.*}-WC.csv"
    sed -i '/,HI,/d' "$file"
    rg ,AK, "$file" >>"${file%.*}-WC.csv"
    sed -i '/,AK,/d' "$file"
    rg ,MT, "$file" >>"${file%.*}-WC.csv"
    sed -i '/,MT,/d' "$file"
    rg ,ID, "$file" >>"${file%.*}-WC.csv"
    sed -i '/,ID,/d' "$file"
    rg ,WY, "$file" >>"${file%.*}-WC.csv"
    sed -i '/,WY,/d' "$file"
    rg ,UT, "$file" >>"${file%.*}-WC.csv"
    sed -i '/,UT,/d' "$file"
    rg ,CO, "$file" >>"${file%.*}-WC.csv"
    sed -i '/,CO,/d' "$file"
    rg ,AZ, "$file" >>"${file%.*}-WC.csv"
    sed -i '/,AZ,/d' "$file"
    rg ,NM, "$file" >>"${file%.*}-WC.csv"
    sed -i '/,NM,/d' "$file"
    rg ,ND, "$file" >>"${file%.*}-EC.csv"
    sed -i '/,ND,/d' "$file"
    rg ,SD, "$file" >>"${file%.*}-EC.csv"
    sed -i '/,SD,/d' "$file"
    rg ,NE, "$file" >>"${file%.*}-EC.csv"
    sed -i '/,NE,/d' "$file"
    rg ,KS, "$file" >>"${file%.*}-EC.csv"
    sed -i '/,KS,/d' "$file"
    rg ,OK, "$file" >>"${file%.*}-EC.csv"
    sed -i '/,OK,/d' "$file"
    rg ,TX, "$file" >>"${file%.*}-EC.csv"
    sed -i '/,TX,/d' "$file"
    rg ,MN, "$file" >>"${file%.*}-EC.csv"
    sed -i '/,MN,/d' "$file"
    rg ,IA, "$file" >>"${file%.*}-EC.csv"
    sed -i '/,IA,/d' "$file"
    rg ,NO, "$file" >>"${file%.*}-EC.csv"
    sed -i '/,NO,/d' "$file"
    rg ,AR, "$file" >>"${file%.*}-EC.csv"
    sed -i '/,AR,/d' "$file"
    rg ,LA, "$file" >>"${file%.*}-EC.csv"
    sed -i '/,LA,/d' "$file"
    rg ,WI, "$file" >>"${file%.*}-EC.csv"
    sed -i '/,WI,/d' "$file"
    rg ,IL, "$file" >>"${file%.*}-EC.csv"
    sed -i '/,IL,/d' "$file"
    rg ,MS, "$file" >>"${file%.*}-EC.csv"
    sed -i '/,MS,/d' "$file"
    rg ,AL, "$file" >>"${file%.*}-EC.csv"
    sed -i '/,AL,/d' "$file"
    rg ,TN, "$file" >>"${file%.*}-EC.csv"
    sed -i '/,TN,/d' "$file"
    rg ,MO, "$file" >>"${file%.*}-EC.csv"
    sed -i '/,MO,/d' "$file"
    rg ,MI, "$file" >>"${file%.*}-EC.csv"
    sed -i '/,MI,/d' "$file"
    rg ,IN, "$file" >>"${file%.*}-EC.csv"
    sed -i '/,IN,/d' "$file"
    rg ,KY, "$file" >>"${file%.*}-EC.csv"
    sed -i '/,KY,/d' "$file"
    rg ,GA, "$file" >>"${file%.*}-EC.csv"
    sed -i '/,GA,/d' "$file"
    rg ,FL, "$file" >>"${file%.*}-EC.csv"
    sed -i '/,FL,/d' "$file"
    rg ,OH, "$file" >>"${file%.*}-EC.csv"
    sed -i '/,OH,/d' "$file"
    rg ,WV, "$file" >>"${file%.*}-EC.csv"
    sed -i '/,WV,/d' "$file"
    rg ,SC, "$file" >>"${file%.*}-EC.csv"
    sed -i '/,SC,/d' "$file"
    rg ,PA, "$file" >>"${file%.*}-EC.csv"
    sed -i '/,PA,/d' "$file"
    rg ,VA, "$file" >>"${file%.*}-EC.csv"
    sed -i '/,VA,/d' "$file"
    rg ,NC, "$file" >>"${file%.*}-EC.csv"
    sed -i '/,NC,/d' "$file"
    rg ,NY, "$file" >>"${file%.*}-EC.csv"
    sed -i '/,NY,/d' "$file"
    rg ,NJ, "$file" >>"${file%.*}-EC.csv"
    sed -i '/,NJ,/d' "$file"
    rg ,MD, "$file" >>"${file%.*}-EC.csv"
    sed -i '/,MD,/d' "$file"
    rg ,DE, "$file" >>"${file%.*}-EC.csv"
    sed -i '/,DE,/d' "$file"
    rg ,ME, "$file" >>"${file%.*}-EC.csv"
    sed -i '/,ME,/d' "$file"
    rg ,VT, "$file" >>"${file%.*}-EC.csv"
    sed -i '/,VT,/d' "$file"
    rg ,NH, "$file" >>"${file%.*}-EC.csv"
    sed -i '/,NH,/d' "$file"
    rg ,MA, "$file" >>"${file%.*}-EC.csv"
    sed -i '/,MA,/d' "$file"
    rg ,CT, "$file" >>"${file%.*}-EC.csv"
    sed -i '/,CT,/d' "$file"
    rg ,RI, "$file" >>"${file%.*}-EC.csv"
    sed -i '/,RI,/d' "$file"
    rg ,DC, "$file" >>"${file%.*}-EC.csv"
    sed -i '/,DC,/d' "$file"

    mv "$file" "${file%.*}-no-tz.csv"
done
