#!/bin/sh

EXPECTED_ARGS=2
E_BADARGS=65
MYSQL=$(which mariadb)

Q1="CREATE DATABASE IF NOT EXISTS $1;"
Q2="GRANT ALL ON $1.* TO '$2'@'localhost';"
Q3="FLUSH PRIVILEGES;"
SQL="${Q1}${Q2}${Q3}"

if [ $# -ne $EXPECTED_ARGS ]; then
    echo "Usage: $0 dbname dbuser dbpass"
    exit $E_BADARGS
fi

$MYSQL --defaults-file=/home/ryanm/.local/share/mysql/config -e "$SQL"

#green "Database $1 and user $2 created with a password you chose"
