#!/usr/bin/env python

import pandas as pd

in_file = "master-archive-clean.csv"
out_file = "new-master-archive-clean.csv"

fields = [
    "General Contact Profile\\Middle Name",
    "General Contact Profile\\Address - Street",
    "General Contact Profile\\Address - City",
    "General Contact Profile\\Address - Zip",
    "General Contact Profile\\Phone Number",
    "General Contact Profile\\WorkAdd - Street",
    "General Contact Profile\\WorkAdd - City",
    "General Contact Profile\\WorkAdd - State",
    "General Contact Profile\\WorkAdd - Zip",
    "General Contact Profile\\Work Phone Number",
    "General Contact Profile\\License Type",
    "General Contact Profile\\License Status",
    "General Contact Profile\\Pkg Price",
    "General Contact Profile\\Address - Street 2",
    "General Contact Profile\\WorkAdd - Street 2",
    "General Contact Profile\\DOB-mmddyyyy",
    "General Contact Profile\\LicBeg-mmddyyyy",
    "General Contact Profile\\DOB",
    "General Contact Profile\\LicExp-mmddyyyy",
    "General Contact Profile\\Bounced by Email Provider",
    "General Contact Profile\\CustomerID",
    "General Contact Profile\\DBsource",
    "General Contact Profile\\License Number",
    "General Contact Profile\\Subscribe Date - orig.",
    "General Contact Profile\\State - nonRes. Source",
    "General Contact Profile\\Resident",
    "General Contact Profile\\Address - Country",
    "General Contact Profile\\CustomerCompanyID",
    "General Contact Profile\\Registration Date",
    "General Contact Profile\\TransferFrom",
    "Last Open Date (UTC-05)",
    "Last Read Date (UTC-05)",
    "Last Click Date (UTC-05)",
    "Last Send Date (UTC-05)",
    "Country",
    "Region",
    "Postal Code",
    "Preferred Email Client",
    "Email Key",
    "Universal Email Key (SHA256)",
    "23",
    "24",
    "13",
    "29",
    "31",
    "19",
    "25",
    "18",
    "14",
    "30",
    "9",
    "54",
    "53",
    "Complete General Contact Profile\\Subscribe Date - orig.",
    "Complete General Contact Profile\\Database",
    "Complete General Contact Profile\\First Name",
    "Complete General Contact Profile\\Last Name",
    "Complete General Contact Profile\\Title",
    "Complete General Contact Profile\\Company",
    "Complete General Contact Profile\\Address - Street",
    "Complete General Contact Profile\\Address - Street 2",
    "Complete General Contact Profile\\Address - City",
    "Complete General Contact Profile\\Address - State",
    "Complete General Contact Profile\\Address - Zip",
    "Complete General Contact Profile\\Phone Number",
    "Complete General Contact Profile\\WorkAdd - Street",
    "Complete General Contact Profile\\WorkAdd - Street 2",
    "Complete General Contact Profile\\WorkAdd - City",
    "Complete General Contact Profile\\WorkAdd - State",
    "Complete General Contact Profile\\WorkAdd - Zip",
    "Complete General Contact Profile\\Work Phone Number",
    "Complete General Contact Profile\\License Type",
    "Complete General Contact Profile\\Licensed CFP Yes-No",
    "Complete General Contact Profile\\DOB-mmddyyyy",
    "Complete General Contact Profile\\LicExp-mmddyyyy",
    "Complete General Contact Profile\\LicBeg-mmddyyyy",
    "Complete General Contact Profile\\Pkg Price",
    "Complete General Contact Profile\\List Source",
    "Complete General Contact Profile\\Address - Country",
    "Complete General Contact Profile\\IsCustomer",
    "Complete General Contact Profile\\License Number",
    "Complete General Contact Profile\\Middle Name",
    "Complete General Contact Profile\\DB Source",
    "10",
    "11",
    "12",
    "16",
    "15",
    "17",
    "8",
    "26",
    "27",
    "40",
    "Complete General Contact Profile\\Email Address",
    "Complete General Contact Profile\\Full Name",
    "Complete General Contact Profile\\Address - St.-City-State-Zip",
    "Complete General Contact Profile\\Phone Number (Area Only)",
    "Complete General Contact Profile\\WorkAdd - Full",
    "Complete General Contact Profile\\Work Phone Number (Area)",
    "Complete General Contact Profile\\Subscribe Date",
    "Complete General Contact Profile\\NPN",
    "Complete General Contact Profile\\Database Acquired",
    "Complete General Contact Profile\\Group",
    "Complete General Contact Profile\\Upload Date",
    "Complete General Contact Profile\\Mailigen_List",
    "Complete General Contact Profile\\DBsource",
    "Complete General Contact Profile\\CustomerID",
    "Complete General Contact Profile\\CustomerCompanyID",
    "Complete General Contact Profile\\TransferFrom",
    "Complete General Contact Profile\\IsCustomer Yes-No",
    "Database\\Crump",
    "Database\\Vantis1",
    "Database\\SLA",
    "Database\\WA Annuity Students",
    "Database\\WA ALL OTHERS",
    "WA Annuity Students\\Database",
    "WA Annuity Students Special Email\\WA Annuity Students Special Email",
    "Customer\\Database",
    "Customer\\Full Name",
    "Customer\\Email",
    "Customer\\RegistrationDate",
    "Customer\\Address - City",
    "Customer\\Address - Country",
    "Customer\\Address - Zip",
    "Customer\\License Number",
    "Customer\\Address - State",
    "Customer\\LastUpdated",
    "Customer\\prelicense_completed",
    "Deliverability\\Warmup Segment",
    "Complete General Contact Profile\\License Status",
    "Complete General Contact Profile\\WordAdd - Full",
    "Complete General Contact Profile\\Import Date",
    "Complete General Contact Profile\\Bounced by Email provider",
    "Complete General Contact Profile\\State - non.res Source",
    "Complete General Contact Profile\\Resident",
    "Complete General Contact Profile\\CE Compliance",
    "Complete General Contact Profile\\Address - Province",
    "Complete General Contact Profile\\z_IsAffiliate",
    "Complete General Contact Profile\\ExpYr_E-O",
    "Complete General Contact Profile\\AccountRegistrationDate",
    "Complete General Contact Profile\\AffiliateName",
    "Complete General Contact Profile\\RegistrationDate",
    "Complete General Contact Profile\\Year",
    "General Contact Info\\Company",
    "General Contact Info\\Last Name",
    "General Contact Info\\First Name",
    "SILA2018",
    "Profile Info\\First Name",
    "Profile Info\\Last Name",
    "Profile Info\\Subscribe Date",
    "Profile Info\\Address - Street",
    "Profile Info\\Address - Street 2",
    "Profile Info\\Address - City",
    "Profile Info\\Address - State",
    "Profile Info\\Address - Zip",
    "Profile Info\\Phone Number",
    "Profile Info\\WorkAdd - Street",
    "Profile Info\\WorkAdd - Street 2",
    "Profile Info\\WorkAdd - City",
    "Profile Info\\WorkAdd - State",
    "Profile Info\\WorkAdd - Zip",
    "Profile Info\\Work Phone Number",
    "Profile Info\\DOB-mmddyyyy",
    "Profile Info\\LicExp-mmddyyyy",
    "Profile Info\\LicBeg-mmddyyyy",
    "Profile Info\\License Number",
    "Profile Info\\NPN",
    "WFG",
    "Profile Info\\Agent Code Number",
    "Profile Info\\Full Name",
    "Profile Info\\Address - Country",
    "Profile Info\\Work Address Full",
    "Profile Info\\Middle Name",
    "Profile Info\\DB Source",
    "Profile Info\\IsCustomer_Yes-No",
    "Profile Info\\Address - Province",
    "Profile Info\\Customer ID",
    "Profile Info\\Company",
    "Profile Info\\RegistrationDate",
    "Profile Info\\WFGAgentCode",
    "Profile Info\\Subscribe Date - orig.",
    "Profile Info\\TransferFrom",
    "CFP",
    "Subscribe Date (UTC-05)_2",
    "Complete General Contact Profile\\ID",
    "Complete General Contact Profile\\CE Requirement Status",
    "Complete General Contact Profile\\Hours Remaining",
    "Complete General Contact Profile\\CE Requirement Type",
    "Complete General Contact Profile\\Country",
    "Database\\Work - Email",
    "VRBO\\Property",
    "VRBO\\Check-in",
    "VRBO\\Check-out",
    "VRBO\\Nights Stay",
    "VRBO\\Adults",
    "VRBO\\Children",
    "Profile\\Last Name",
    "Profile\\First Name",
    "Profile\\Phone",
    "Profile\\CrsTaken",
    "Profile\\Company",
    "Primerica Agent Profile\\First Name",
    "Primerica Agent Profile\\Last Name",
    "Primerica Agent Profile\\Title",
    "Primerica Agent Profile\\Company",
    "Primerica Agent Profile\\Address - State",
    "Primerica Agent Profile\\WorkAdd - Street",
    "Primerica Agent Profile\\WorkAdd - City",
    "Primerica Agent Profile\\WorkAdd - State",
    "Primerica Agent Profile\\WorkAdd - Zip",
    "Primerica Agent Profile\\DOB-mmddyyyy",
    "Primerica Agent Profile\\LicExp-mmddyyyy",
    "Primerica Agent Profile\\LicBeg-mmddyyyy",
    "Last Name\\Last Name",
    "Last Name\\First Name",
    "Last Name\\State",
    "Last Name\\License Type",
    "Last Name\\Product Training",
    "Last Name\\Paragraph1",
    "Last Name\\Paragraph2",
    "Last Name\\Paragraph3",
    "Last Name\\Paragraph4",
    "Basic\\Last Name",
    "Basic\\First Name",
    "Basic\\Company",
    "Management",
    "RIA",
    "FM",
    "FirstChoice",
    "LF-Internal",
    "Lead",
    "NAPSLO",
    "New Big A",
    "Unsubscribe Date (UTC-05)_2",
    "New Big B",
    "PrimericaRS",
    "SLO",
    "Vantis",
    "Vantis1\\FirstName",
    "Vantis1\\LastName",
    "Vantis1\\State",
]

# Load the CSV file into a DataFrame
df = pd.read_csv(in_file, dtype=str, on_bad_lines="skip")

# Remove the specified column
df.drop(columns=fields, inplace=True)

# write to file
df.to_csv(out_file, index=False)
