#!/bin/sh
hyprctl binds -j | \
  jq -r '.[] | "\(.modmask // "none") + \(.key // .keycode)  →  \(.dispatcher) \(.arg // "")"' | \
  sort -u | \
  bemenu -i -p "keybind:" \
    --bottom --line-height 30 --fn "JetBrainsMonoNerdFontMono 14" \
    --tb "#15191c" --tf "#b7bdf8" --fb "#15191c" --ff "#d3c6aa" \
    --nb "#15191c" --nf "#4b565c" --hb "#15191c" --hf "#d3c6aa"
